"""Add relationships to models

Revision ID: edb723dc7cc9
Revises: 1a660c242acb
Create Date: 2024-07-30 19:53:45.143261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb723dc7cc9'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baked_goods', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('baked_goods', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baked_goods', 'bakery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baked_goods', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
